-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.class_settings
(
    teacher_id uuid NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT class_settings_pkey PRIMARY KEY (teacher_id, key)
);

ALTER TABLE IF EXISTS public.class_settings
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.curriculum_topics
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    grade integer NOT NULL,
    plnn_level character varying(10) COLLATE pg_catalog."default" NOT NULL,
    domain character varying(50) COLLATE pg_catalog."default" NOT NULL,
    topic_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT curriculum_topics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exercises_g3_g4
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    grade integer NOT NULL,
    module_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prompt text COLLATE pg_catalog."default" NOT NULL,
    content jsonb NOT NULL,
    plnn_level character varying(10) COLLATE pg_catalog."default" DEFAULT 'A1'::character varying,
    topic_id uuid,
    CONSTRAINT exercises_g3_g4_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grammar_parameters
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    teacher_id uuid,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    base_word character varying(100) COLLATE pg_catalog."default" NOT NULL,
    target_word character varying(100) COLLATE pg_catalog."default" NOT NULL,
    feature_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    plnn_level character varying(5) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A1'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT grammar_parameters_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.phrases
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    teacher_id uuid,
    phrase_text text COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    plnn_level character varying(5) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A1'::character varying,
    target_word character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT phrases_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_progress
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    student_id uuid NOT NULL,
    word_id text COLLATE pg_catalog."default",
    stage integer NOT NULL DEFAULT 0,
    written_sentence text COLLATE pg_catalog."default",
    attempts integer DEFAULT 1,
    teacher_status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    teacher_feedback text COLLATE pg_catalog."default",
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    exercise_type text COLLATE pg_catalog."default" DEFAULT 'word'::text,
    phrase_id bigint,
    verb_id bigint,
    grammar_id bigint,
    CONSTRAINT student_progress_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.student_progress
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.students
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pin character varying(10) COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    plnn_level character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A1'::character varying,
    teacher_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT students_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teachers
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    school text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    pin text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT teachers_pkey PRIMARY KEY (id),
    CONSTRAINT teachers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.verb_conjugations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    verb_id bigint,
    tense character varying(50) COLLATE pg_catalog."default" NOT NULL,
    person character varying(20) COLLATE pg_catalog."default" NOT NULL,
    conjugated_form character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT verb_conjugations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.verbs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    teacher_id uuid,
    infinitive character varying(100) COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    plnn_level character varying(5) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A1'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT verbs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.words
(
    id text COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    word text COLLATE pg_catalog."default" NOT NULL,
    emoji text COLLATE pg_catalog."default" NOT NULL,
    hint text COLLATE pg_catalog."default" NOT NULL,
    blank_before text COLLATE pg_catalog."default",
    blank_after text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    plnn_level character varying(10) COLLATE pg_catalog."default" DEFAULT 'A1'::character varying,
    topic_id uuid,
    CONSTRAINT words_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.words
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.exercises_g3_g4
    ADD CONSTRAINT exercises_g3_g4_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.curriculum_topics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grammar_parameters
    ADD CONSTRAINT grammar_parameters_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.phrases
    ADD CONSTRAINT phrases_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_progress
    ADD CONSTRAINT fk_student_progress_student FOREIGN KEY (student_id)
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_progress
    ADD CONSTRAINT student_progress_grammar_id_fkey FOREIGN KEY (grammar_id)
    REFERENCES public.grammar_parameters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_progress
    ADD CONSTRAINT student_progress_phrase_id_fkey FOREIGN KEY (phrase_id)
    REFERENCES public.phrases (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_progress
    ADD CONSTRAINT student_progress_verb_id_fkey FOREIGN KEY (verb_id)
    REFERENCES public.verbs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT fk_students_teacher FOREIGN KEY (teacher_id)
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.verb_conjugations
    ADD CONSTRAINT verb_conjugations_verb_id_fkey FOREIGN KEY (verb_id)
    REFERENCES public.verbs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.verbs
    ADD CONSTRAINT verbs_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.words
    ADD CONSTRAINT words_topic_id_fkey FOREIGN KEY (topic_id)
    REFERENCES public.curriculum_topics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;